# Generated by Django 2.2.4 on 2020-08-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='datetime',
        ),
    ]
